server:
  port: 8081

spring:
  application:
    name: price-service
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:price-service
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2
      mode: always
      schema-locations: classpath:init-schema.sql

h2:
  console:
    enabled: true
    path: /h2-console
    settings:
      trace: false
      web-allow-others: true

logging:
  level:
    org.hibernate.sql: DEBUG